language: cpp

sudo: required

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      osx_image: xcode7.1
      compiler: clang
    
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; 
    then 
      brew update > /dev/null 2>&1;
      brew install --quite cmake;
      brew install --quite boost;
      brew install --quiet tbb --c++11;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
    then 
      sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x;
      sudo apt-get update -qq;
      sudo apt-get purge -qq cmake;
      sudo apt-get install -qq cmake;
      cmake --version;
      sudo apt-get install -qq libboost-dev libtbb-dev;
    fi

before_script:
  - cmake .;

script:
  - export OMP_NUM_THREADS=2;
  - make;
  - ./MatrixMultiply; 
    
notifications:
  email:
    on_success: change
    on_failure: always
